[credential]
    [credential.consumer]
        key = your_key
        secret = your_secret
    
    [credential.access]
        token = your_token
        secret = your_secret

[news]
    api_key = your_news_api_key (https://newsapi.org/docs)\
